name: run-python-script

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.event.outputs.input}}
    steps:
    - uses: actions/checkout@v3
      
    - name: Run Main Script
      id: event
      run: |
          bash scripts/sample.sh >> status.log
          echo "input=$(cat status.log)" >> $GITHUB_OUTPUT 
          # echo $input
          # echo "::set-output name=params::$input"    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt  
    - name: Run Event Script
      run: | 
        
        python event.py  --params ${{ toJson(needs.job1.outputs.output1)}}

