name: run-python-script

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.event.outputs.params}}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Main Script
      id: event
      run: | 
          input=$(python main.py) 
          echo $input
          # output_var=$(cat dummy.txt)
          echo "::set-output name=params::$input"    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt  
    - name: Run Event Script
      run: | 
        echo "${{ toJson(needs.job1.outputs.output1)}}"
        python event.py  --params ${{ toJson(needs.job1.outputs.output1)}}

